project:
  type: book
  output-dir: _book

book:
  title: "One Seven Project"
  reader-mode: true

  page-footer:
    left: |
      One seven project.
    right: |
      This site was built with <a href="https://quarto.org/">Quarto</a>.
  # site-url: https://r4ds.hadley.nz/
  repo-url: https://github.com/sepmein/one_seven
  repo-branch: master
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - part: qmd/01_data/01_00_data.qmd
      chapters:
        - qmd/01_data/01_01_data_code.qmd

format:
  html:
    theme:
      - cosmo
    code-link: true

editor: visual
