project:
  type: book
  output-dir: _book

book:
  title: "One Seven Project"
  reader-mode: true

  page-footer:
    left: |
      One seven project.
    right: |
      This site was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/sepmein/one-seven
  repo-branch: master
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - part: qmd/01_data/01_00_data.qmd
      chapters:
        - qmd/01_data/01_01_meta_data.qmd
        - qmd/01_data/01_02_data_code.qmd
        - qmd/01_data/01_03_dhis2_data.qmd
        - qmd/01_data/01_04_survey_household.qmd
        - qmd/01_data/01_05_survey_household_member.qmd
        - qmd/01_data/01_06_survey_net_use.qmd
        - qmd/01_data/01_07_survey_child.qmd
        - qmd/01_data/01_08_survey_visit.qmd

    - part: qmd/02_analysis/02_00_analysis.qmd
      chapters:
        - qmd/02_analysis/02_01_methodology.qmd

    - part: Zambia
      chapters:
        - qmd/02_analysis/02_11_zam/02_11_01_analysis_file_creation.qmd
        - qmd/02_analysis/02_11_zam/02_11_04_data_overview.qmd

format:
  html:
    theme:
      - cosmo
    code-link: true

editor: visual
