---
title: "One Seven Project"
---

# Introduction

The One Seven Project is a multi-country initiative aimed at reducing the malaria disease burden through the implementation of an innovative strategy known as the 17-malaria Reactive Community-based Testing and Response (17-mRCTR) approach. This approach builds upon previous successful malaria control interventions, adapting them to the unique epidemiological contexts of four African countries: Burkina Faso, Zambia, Senegal, and Tanzania.

## Background

Malaria continues to be a major public health challenge in many parts of Africa, where the progress towards its elimination has stalled. Despite the widespread use of interventions such as insecticide-treated nets (ITNs) and artemisinin-based combination therapies (ACTs), many high-transmission areas still experience significant levels of morbidity and mortality. The One Seven Project addresses these challenges by enhancing community-based surveillance and response systems.

## The 17-mRCTR Approach

The 17-mRCTR approach is an adaptation of the "1-3-7" malaria elimination strategy, which was originally developed in China. This approach emphasizes rapid detection and response to malaria cases within communities. Specifically, it involves: - **Day 1**: Reporting of confirmed malaria cases. - **Day 7**: Community-level testing and treatment interventions based on real-time surveillance data.

This strategy has been locally tailored to the high transmission settings in Africa, where the malaria burden remains high. By focusing on community-based interventions, the 17-mRCTR approach aims to reduce the malaria incidence ratio (MIR) and improve the overall health outcomes in the target areas.

## Project Objectives

The primary objective of the One Seven Project is to validate the effectiveness of the 17-mRCTR approach in different epidemiological settings. By doing so, the project seeks to establish a scalable model for malaria control that can be implemented across other high-burden regions. Specific goals include: - Reducing malaria prevalence and incidence in the intervention areas. - Enhancing the capacity of local health systems to respond to malaria outbreaks. - Engaging communities in proactive health-seeking behaviors and adherence to malaria prevention measures.

```{r}
#| label: install_packages
#| echo: false
#| message: false
#| warning: false

# make sure the required packages were installed

if (!requireNamespace("pacman", quietly = TRUE)) {
  install.packages("pacman")
}

library(pacman)

pacman::p_load('here')
pacman::p_load('plotly')
pacman::p_load('sparkline')
pacman::p_load('gt')
pacman::p_load('qs')
pacman::p_load('formatR')
```
